# Data Cleaning & Preparation

## Objective

Transform the audited raw retail transaction data into a **consistent, reliable, and analysis-ready dataset** while preserving the original source data.

The cleaning process addresses data-quality issues identified during the initial audit, including missing values, duplicate records, inconsistent categorical values, mixed date formats, invalid numerical values, and business-rule anomalies.

## Data Preparation Approach

The cleaning process follows a controlled and reproducible workflow:

- Preserve the raw dataset as the source of truth.
- Perform transformations on a separate working copy.
- Apply business-context-driven cleaning decisions rather than indiscriminate row deletion.
- Validate data after each major transformation.
- Document significant assumptions and treatment decisions.
- Maintain a reproducible path from raw data to the final cleaned dataset.

## Cleaning Scope

1. Duplicate detection and removal
2. Categorical value standardization
3. Date parsing and standardization
4. Missing-value treatment
5. Numerical data validation
6. Business-rule validation
7. Final data-quality verification

## Deliverable

A validated, analysis-ready dataset suitable for:

- Exploratory Data Analysis
- Business analysis and KPI development
- Power BI reporting
- Reusable Python data-processing workflows

In [1]:
from multiprocessing.reduction import duplicate

import pandas as pd
from pandas.core.algorithms import value_counts_internal

In [2]:
df_raw=pd.read_csv('../data/raw/Project_1_Raw_Retail_Sales.csv')
df_raw.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Region,State,City,Category,Subcategory,Product,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Payment_Method,Sales_Channel,Order_Status
0,ORD-003886,2025-10-31 20:49:55,11279,Aarav Patel,North,Delhi,Delhi,Electronics,Smartphones,Nova X5,1,21280.44,0.00,21280.44,16087.18,5193.26,Debit Card,Online,Delivered
1,ORD-039073,2025-03-08 04:49:07,13949,Priya Mehta,East,Bihar,Patna,Electronics,Smartphones,ZenPhone Lite,1,14888.11,0.20,11910.49,10801.13,1109.35,UPI,Store,Delivered
2,ORD-034360,2024-03-19 11:48:17,10252,Priya Reddy,North,Uttarakhand,Dehradun,Electronics,Smartphones,PixelMax A2,2,18560.63,0.05,35265.20,23705.16,11560.04,Credit Card,Online,Delivered
3,ORD-010240,11/07/2024,12307,Ishaan Mehta,South,Kerala,Kochi,Home & Kitchen,Kitchenware,Storage Set,2,1522.45,0.05,2892.66,2117.20,775.46,Debit Card,Online,Delivered
4,ORD-035487,2024-09-15 00:27:26,10731,Ananya Reddy,South,Kerala,Kochi,Furniture,Office,Study Desk,1,9309.10,0.05,8843.65,7120.30,1723.34,Cash on Delivery,online,Cancelled

In [3]:
df=df_raw.copy()
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Region,State,City,Category,Subcategory,Product,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Payment_Method,Sales_Channel,Order_Status
0,ORD-003886,2025-10-31 20:49:55,11279,Aarav Patel,North,Delhi,Delhi,Electronics,Smartphones,Nova X5,1,21280.44,0.00,21280.44,16087.18,5193.26,Debit Card,Online,Delivered
1,ORD-039073,2025-03-08 04:49:07,13949,Priya Mehta,East,Bihar,Patna,Electronics,Smartphones,ZenPhone Lite,1,14888.11,0.20,11910.49,10801.13,1109.35,UPI,Store,Delivered
2,ORD-034360,2024-03-19 11:48:17,10252,Priya Reddy,North,Uttarakhand,Dehradun,Electronics,Smartphones,PixelMax A2,2,18560.63,0.05,35265.20,23705.16,11560.04,Credit Card,Online,Delivered
3,ORD-010240,11/07/2024,12307,Ishaan Mehta,South,Kerala,Kochi,Home & Kitchen,Kitchenware,Storage Set,2,1522.45,0.05,2892.66,2117.20,775.46,Debit Card,Online,Delivered
4,ORD-035487,2024-09-15 00:27:26,10731,Ananya Reddy,South,Kerala,Kochi,Furniture,Office,Study Desk,1,9309.10,0.05,8843.65,7120.30,1723.34,Cash on Delivery,online,Cancelled

In [4]:
df_raw.shape

(50150, 19)

In [5]:
df.shape

(50150, 19)

In [6]:
df_raw is df

False

In [7]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Region',
       'State', 'City', 'Category', 'Subcategory', 'Product', 'Quantity',
       'Unit_Price', 'Discount', 'Sales', 'Cost', 'Profit', 'Payment_Method',
       'Sales_Channel', 'Order_Status'],
      dtype='str')

In [8]:
df.columns=[x.lower() for x in df.columns]

In [9]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'customer_name', 'region',
       'state', 'city', 'category', 'subcategory', 'product', 'quantity',
       'unit_price', 'discount', 'sales', 'cost', 'profit', 'payment_method',
       'sales_channel', 'order_status'],
      dtype='str')

In [10]:
df.columns.duplicated().sum()

np.int64(0)

In [11]:
df.duplicated().sum()

np.int64(150)

In [12]:
df[df.duplicated()].head()

,order_id,order_date,customer_id,customer_name,region,state,city,category,subcategory,product,quantity,unit_price,discount,sales,cost,profit,payment_method,sales_channel,order_status
3591,ORD-046498,2025-01-12 18:21:54,14318,Kavya Reddy,West,Gujarat,Surat,Home & Kitchen,Appliances,Air Fryer,2,6400.81,0.15,10881.37,8425.82,2455.55,UPI,Online,Delivered
4614,ORD-045093,2025-05-23 04:13:20,11102,Isha Singh,West,Maharashtra,Mumbai,Fashion,Women,Handbag,4,1793.87,0.05,6816.69,4510.93,2305.76,Net Banking,Store,Cancelled
4863,ORD-020845,2025-04-14 04:13:26,15854,Meera Mehta,South,Andhra Pradesh,Vijayawada,Electronics,Accessories,Wireless Earbuds,1,3047.81,0.00,3047.81,1680.05,1367.75,Credit Card,Store,Delivered
5893,ORD-001108,2025-10-03 02:08:49,12790,Kavya Patel,South,Telangana,Hyderabad,Fashion,Women,Kurti,1,1190.40,0.00,1190.40,747.81,442.58,UPI,Online,Delivered
6413,ORD-040607,02/02/2025,10451,Isha Patel,West,Gujarat,Ahmedabad,Electronics,Smartphones,Nova X5,2,23020.78,0.00,46041.56,25198.57,20842.99,UPI,online,Delivered

In [13]:
df=df.drop_duplicates()

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df['region'].unique()

<StringArray>
['North', 'East', 'South', 'WEST', 'West', 'north', 'south']
Length: 7, dtype: str

In [16]:
df['region']=df['region'].replace({'north':'North','WEST':'West','south':'South'})

In [17]:
df['region'].unique()

<StringArray>
['North', 'East', 'South', 'West']
Length: 4, dtype: str

In [18]:
df['payment_method'].unique()

<StringArray>
[      'Debit Card',              'UPI',      'Credit Card',
 'Cash on Delivery',              'upi',      'Net Banking',
      'credit card',                nan]
Length: 8, dtype: str

In [19]:
df['payment_method']=df['payment_method'].replace({'UPI':'Upi','credit card':'Credit Card','upi':'Upi'})

In [20]:
df['payment_method'].unique()

<StringArray>
['Debit Card', 'Upi', 'Credit Card', 'Cash on Delivery', 'Net Banking', nan]
Length: 6, dtype: str

In [21]:
df['sales_channel'].unique()

<StringArray>
['Online', 'Store', 'online', 'store']
Length: 4, dtype: str

In [22]:
df['sales_channel']=df['sales_channel'].replace({'online':'Online','store':'Store'})

In [23]:
df['sales_channel'].unique()

<StringArray>
['Online', 'Store']
Length: 2, dtype: str

In [24]:
df.dtypes['order_date']

In [25]:
df['order_date'].head(20)

0     2025-10-31 20:49:55
1     2025-03-08 04:49:07
2     2024-03-19 11:48:17
3              11/07/2024
4     2024-09-15 00:27:26
5     2024-12-08 07:06:14
6     2025-03-04 11:30:21
7     2024-10-24 07:04:20
8     2024-06-13 09:02:39
9     2024-03-03 14:33:32
10    2025-07-25 03:28:30
11    2025-10-01 15:54:59
12    2024-03-12 05:21:29
13    2024-09-01 19:59:49
14    2024-04-16 08:09:00
15    2024-01-15 19:10:50
16    2025-09-03 07:05:10
17    2025-03-10 12:18:24
18    2024-05-01 23:07:48
19    2024-07-01 23:58:44
Name: order_date, dtype: str

In [26]:
df['order_date']=pd.to_datetime(df['order_date'],format='mixed')

In [27]:
df['order_date'].dtype

dtype('<M8[us]')

In [28]:
df['order_date'].isnull().sum()

np.int64(0)

In [29]:
df['order_date'].head(10)

0   2025-10-31 20:49:55
1   2025-03-08 04:49:07
2   2024-03-19 11:48:17
3   2024-11-07 00:00:00
4   2024-09-15 00:27:26
5   2024-12-08 07:06:14
6   2025-03-04 11:30:21
7   2024-10-24 07:04:20
8   2024-06-13 09:02:39
9   2024-03-03 14:33:32
Name: order_date, dtype: datetime64[us]

In [30]:
df['order_date'].min()

Timestamp('2024-01-01 00:00:00')

In [31]:
df['order_date'].max()

Timestamp('2025-12-30 23:38:33')

In [32]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
customer_name     600
region              0
state               0
city              400
category            0
subcategory         0
product             0
quantity            0
unit_price          0
discount          500
sales               0
cost                0
profit              0
payment_method    300
sales_channel       0
order_status        0
dtype: int64

In [33]:
[column for column in df.columns if df[column].isnull().sum()>0.]

['customer_name', 'city', 'discount', 'payment_method']

In [34]:
df.isnull().sum()[df.isnull().sum() > 0]

customer_name     600
city              400
discount          500
payment_method    300
dtype: int64

In [35]:
df['customer_name']=df['customer_name'].fillna('Unknown')

In [36]:
df['city']=df['city'].fillna('Unknown')

In [37]:
df['payment_method']=df['payment_method'].fillna('Unknown')

In [38]:
df['discount']=df['discount'].fillna(0)

In [39]:
df.isnull().sum()

order_id          0
order_date        0
customer_id       0
customer_name     0
region            0
state             0
city              0
category          0
subcategory       0
product           0
quantity          0
unit_price        0
discount          0
sales             0
cost              0
profit            0
payment_method    0
sales_channel     0
order_status      0
dtype: int64

In [40]:
df.loc[df['quantity']<=0,'quantity']

7588    -1
7873    -1
9880    -1
18578   -1
22722   -1
22767   -1
28741   -1
47251   -1
Name: quantity, dtype: int64

In [41]:
df.loc[df['unit_price']<=0,'unit_price']

2894    -250.0
6581    -250.0
22802   -250.0
26621   -250.0
28354   -250.0
28439   -250.0
36852   -250.0
38010   -250.0
46706   -250.0
Name: unit_price, dtype: float64

In [42]:
df.loc[df['discount']<0,'discount']

Series([], Name: discount, dtype: float64)

In [43]:
df.loc[df['discount']>1,'discount']

3324     1.5
8457     1.5
15817    1.5
25096    1.5
26908    1.5
39243    1.5
42068    1.5
44096    1.5
Name: discount, dtype: float64

In [44]:
df[df['quantity']<=0].shape

(8, 19)

In [45]:
df[df['unit_price']<=0].shape

(9, 19)

In [46]:
df[df['discount']<0].shape

(0, 19)

In [47]:
df[df['discount']>1].shape

(8, 19)

In [48]:
df.loc[df['quantity']<=0,['order_id','product','quantity','unit_price','discount','sales','cost','profit','order_status']]

,order_id,product,quantity,unit_price,discount,sales,cost,profit,order_status
7588,ORD-024760,Fast Charger,-1,1429.25,0.25,3215.81,2796.40,419.42,Returned
7873,ORD-041130,Fast Charger,-1,1430.63,0.05,2718.21,1804.61,913.60,Returned
9880,ORD-013587,Fast Charger,-1,1540.81,0.15,3929.07,2833.55,1095.52,Delivered
18578,ORD-009419,Kurti,-1,1184.16,0.10,1065.75,798.53,267.21,Delivered
22722,ORD-009211,Kurti,-1,1198.77,0.00,1198.77,902.39,296.38,Returned
22767,ORD-039306,Denim Jeans,-1,2093.19,0.00,2093.19,1644.24,448.95,Returned
28741,ORD-017764,Bookshelf,-1,5928.02,0.05,11263.24,7638.95,3624.29,Delivered
47251,ORD-018995,Fast Charger,-1,1477.40,0.20,1181.92,897.37,284.55,Delivered

In [49]:
df=df.drop(df[df['quantity']<0].index)

In [50]:
df[df['quantity']<0].shape

(0, 19)

In [51]:
df.loc[df['unit_price']<=0,['order_id','product','quantity','unit_price','discount','sales','cost','profit','order_status']]

,order_id,product,quantity,unit_price,discount,sales,cost,profit,order_status
2894,ORD-008410,Power Bank,3,-250.0,0.25,4513.27,4055.09,458.18,Returned
6581,ORD-005735,Knife Set,4,-250.0,0.15,4036.43,3248.54,787.89,Delivered
22802,ORD-019993,Denim Jeans,1,-250.0,0.25,1878.52,1273.32,605.20,Returned
26621,ORD-017330,Cookware Set,1,-250.0,0.05,3454.35,2296.33,1158.03,Delivered
28354,ORD-022211,Fast Charger,4,-250.0,0.00,5458.48,3963.67,1494.81,Cancelled
28439,ORD-035642,Moisturizer,1,-250.0,0.10,580.14,431.04,149.10,Delivered
36852,ORD-005768,Fast Charger,3,-250.0,0.10,3718.44,3068.52,649.92,Delivered
38010,ORD-032471,Fast Charger,2,-250.0,0.20,2117.78,1826.83,290.95,Delivered
46706,ORD-019087,Denim Jeans,3,-250.0,0.15,5834.47,4030.17,1804.30,Delivered

In [52]:
df=df.drop(df[df['unit_price']<0].index)

In [53]:
df[df['unit_price']<0].shape

(0, 19)

In [54]:
df.loc[df['discount']>1,['order_id','product','quantity','unit_price','discount','sales','cost','profit','order_status']]

,order_id,product,quantity,unit_price,discount,sales,cost,profit,order_status
3324,ORD-027073,Sunscreen,1,767.69,1.5,767.69,514.87,252.82,Delivered
8457,ORD-003564,Wireless Earbuds,1,2784.75,1.5,2784.75,1696.18,1088.58,Delivered
15817,ORD-015200,Power Bank,3,1732.30,1.5,5196.91,3365.10,1831.81,Delivered
25096,ORD-030731,ZenPhone Lite,2,14605.75,1.5,26290.35,19588.75,6701.60,Delivered
26908,ORD-044219,Nova X5,4,21718.76,1.5,86875.06,68076.16,18798.90,Delivered
39243,ORD-042585,Wireless Earbuds,4,2922.66,1.5,10521.59,8293.64,2227.95,Delivered
42068,ORD-009319,Running Shoes,2,2824.77,1.5,5084.59,3597.43,1487.16,Delivered
44096,ORD-040746,Sofa Side Table,1,4405.59,1.5,3965.03,2654.33,1310.71,Delivered

In [55]:
df=df.drop(df[df['discount']>1].index)

In [56]:
df[df['discount']>1].shape

(0, 19)

In [57]:
a=df[['quantity','unit_price','discount']]
a

       quantity  unit_price  discount
0             1    21280.44      0.00
1             1    14888.11      0.20
2             2    18560.63      0.05
3             2     1522.45      0.05
4             1     9309.10      0.05
...         ...         ...       ...
50145         4    18763.34      0.10
50146         1    11557.39      0.25
50147         5     3362.06      0.10
50148         1     2956.79      0.05
50149         1     1793.58      0.15

[49975 rows x 3 columns]

In [58]:
a['new_sales']=a['quantity']*a['unit_price']*(1-a['discount'])
a['new_sales']

0        21280.4400
1        11910.4880
2        35265.1970
3         2892.6550
4         8843.6450
            ...
50145    67548.0240
50146     8668.0425
50147    15129.2700
50148     2808.9505
50149     1524.5430
Name: new_sales, Length: 49975, dtype: float64

In [59]:
compared_sales=pd.concat([df['sales'],a['new_sales']],axis=1)
compared_sales

          sales   new_sales
0      21280.44  21280.4400
1      11910.49  11910.4880
2      35265.20  35265.1970
3       2892.66   2892.6550
4       8843.65   8843.6450
...         ...         ...
50145  67548.02  67548.0240
50146   8668.04   8668.0425
50147  15129.27  15129.2700
50148   2808.95   2808.9505
50149   1524.54   1524.5430

[49975 rows x 2 columns]

In [60]:
sales_difference=df['sales']-a['new_sales']
sales_difference

0        0.0000
1        0.0020
2        0.0030
3        0.0050
4        0.0050
          ...
50145   -0.0040
50146   -0.0025
50147    0.0000
50148   -0.0005
50149   -0.0030
Length: 49975, dtype: float64

In [61]:
sales_difference.abs()

0        0.0000
1        0.0020
2        0.0030
3        0.0050
4        0.0050
          ...
50145    0.0040
50146    0.0025
50147    0.0000
50148    0.0005
50149    0.0030
Length: 49975, dtype: float64

In [62]:
sales_difference.abs() > 0.01

0        False
1        False
2        False
3        False
4        False
         ...
50145    False
50146    False
50147    False
50148    False
50149    False
Length: 49975, dtype: bool

In [63]:
(sales_difference.abs() > 0.01).sum()

np.int64(10686)

In [64]:
pd.concat([df['sales'], a['new_sales'], sales_difference], axis=1).head(10)

      sales   new_sales       0
0  21280.44  21280.4400  0.0000
1  11910.49  11910.4880  0.0020
2  35265.20  35265.1970  0.0030
3   2892.66   2892.6550  0.0050
4   8843.65   8843.6450  0.0050
5   1703.78   1703.7870 -0.0070
6   3562.03   3562.0185  0.0115
7   2777.87   2777.8600  0.0100
8   1241.59   1241.5860  0.0040
9  17159.38  17159.3800  0.0000

In [65]:
sales_difference.abs().describe()

count     49975.000000
mean         87.216702
std        4945.320266
min           0.000000
25%           0.001500
50%           0.004000
75%           0.010000
max      532477.800000
dtype: float64

In [66]:
sales_difference.abs().sort_values(ascending=False).head(10)

40515    532477.800
47172    512136.595
17051    432294.880
7057     428588.220
3244     346118.540
22735    244990.660
41867    188340.790
4181     137397.410
10981    134788.905
46052    132108.195
dtype: float64

In [67]:
df.loc[40515, ['quantity', 'unit_price', 'discount', 'sales', 'cost', 'profit']]

quantity         30.0
unit_price    19721.4
discount          0.0
sales         59164.2
cost          31201.2
profit        27963.0
Name: 40515, dtype: float64

In [68]:
df.loc[47172, ['quantity', 'unit_price', 'discount', 'sales', 'cost', 'profit']]

quantity         30.00
unit_price    18589.35
discount          0.05
sales         17659.88
cost          12003.52
profit         5656.36
Name: 47172, dtype: float64

In [69]:
df[df['quantity'] == 30].shape

(20, 19)

In [70]:
sales_difference[df['quantity']==30]

3244    -346118.540
4181    -137397.410
7057    -428588.220
7838     -70450.030
10981   -134788.905
15741    -12643.785
17051   -432294.880
18617    -62148.600
22534    -36120.670
22735   -244990.660
23124    -53103.060
28500    -38040.530
29929   -112360.000
30833    -31669.470
40515   -532477.800
41110    -45816.200
41867   -188340.790
42176    -30849.760
46052   -132108.195
47172   -512136.595
dtype: float64

In [71]:
(sales_difference.abs() > 100).sum()

np.int64(404)

In [72]:
(sales_difference.abs() > 100).value_counts()

False    49571
True       404
Name: count, dtype: int64

In [73]:
df.loc[sales_difference.abs() > 100, 'quantity'].value_counts()

quantity
2     116
1     112
3      77
5      33
4      33
30     20
6      13
Name: count, dtype: int64

In [74]:
df.loc[(sales_difference.abs() > 100) & (df['quantity'] != 30),['quantity', 'unit_price', 'discount', 'sales']]

       quantity  unit_price  discount     sales
208           2     6422.02       0.0  11559.64
321           2    21938.40       0.0  39489.12
969           2     2721.28       0.0   4898.31
1039          1     1204.91       0.0   1084.42
1098          5     5771.65       0.0  23086.60
...         ...         ...       ...       ...
49015         1     8809.57       0.0   6607.17
49428         5     3719.82       0.0  13949.32
49500         2    14297.64       0.0  27165.51
50060         3     1205.14       0.0   3434.64
50083         3     2519.40       0.0   6802.38

[384 rows x 4 columns]

In [75]:
df.loc[208, ['quantity', 'unit_price', 'discount', 'sales', 'cost', 'profit']]

quantity          2.00
unit_price     6422.02
discount          0.00
sales         11559.64
cost           7011.66
profit         4547.98
Name: 208, dtype: float64

In [76]:
(sales_difference.abs() > 1).sum()

np.int64(431)

In [77]:
(431 / len(df)) * 100

0.862431215607804

In [78]:
a['new_sales'].round(2)

0        21280.44
1        11910.49
2        35265.20
3         2892.66
4         8843.64
           ...
50145    67548.02
50146     8668.04
50147    15129.27
50148     2808.95
50149     1524.54
Name: new_sales, Length: 49975, dtype: float64

In [79]:
a['calculated_sales'] = a['new_sales'].round(2)
a['calculated_sales']

0        21280.44
1        11910.49
2        35265.20
3         2892.66
4         8843.64
           ...
50145    67548.02
50146     8668.04
50147    15129.27
50148     2808.95
50149     1524.54
Name: calculated_sales, Length: 49975, dtype: float64

In [80]:
cmp_sales=pd.concat([a['calculated_sales'],df['sales']],axis=1)
cmp_sales

       calculated_sales     sales
0              21280.44  21280.44
1              11910.49  11910.49
2              35265.20  35265.20
3               2892.66   2892.66
4               8843.64   8843.65
...                 ...       ...
50145          67548.02  67548.02
50146           8668.04   8668.04
50147          15129.27  15129.27
50148           2808.95   2808.95
50149           1524.54   1524.54

[49975 rows x 2 columns]

In [81]:
sales_validation_difference=a['calculated_sales']-df['sales']
sales_validation_difference

0        0.00
1        0.00
2        0.00
3        0.00
4       -0.01
         ...
50145    0.00
50146    0.00
50147    0.00
50148    0.00
50149    0.00
Length: 49975, dtype: float64

In [82]:
sales_validation_difference.abs()>1

0        False
1        False
2        False
3        False
4        False
         ...
50145    False
50146    False
50147    False
50148    False
50149    False
Length: 49975, dtype: bool

In [83]:
(sales_validation_difference.abs() > 1).sum()

np.int64(431)

In [84]:
a['Calculated_Profit'] = a['calculated_sales']-df['cost']
a['Calculated_Profit']

0         5193.26
1         1109.36
2        11560.04
3          775.46
4         1723.34
           ...
50145    19163.56
50146      -74.08
50147     4737.07
50148      680.39
50149      300.52
Name: Calculated_Profit, Length: 49975, dtype: float64

In [85]:
cmp_profit=pd.concat([a['Calculated_Profit'],df['profit']],axis=1)
cmp_profit

       Calculated_Profit    profit
0                5193.26   5193.26
1                1109.36   1109.35
2               11560.04  11560.04
3                 775.46    775.46
4                1723.34   1723.34
...                  ...       ...
50145           19163.56  19163.56
50146             -74.08    -74.07
50147            4737.07   4737.07
50148             680.39    680.39
50149             300.52    300.52

[49975 rows x 2 columns]

In [86]:
profit_validation_difference=a['Calculated_Profit']-df['profit']
profit_validation_difference

0       -1.818989e-12
1        1.000000e-02
2       -3.637979e-12
3        0.000000e+00
4       -6.821210e-13
             ...
50145    3.637979e-12
50146   -1.000000e-02
50147    0.000000e+00
50148   -1.136868e-13
50149    0.000000e+00
Length: 49975, dtype: float64

In [87]:
(profit_validation_difference.abs()>1).sum()

np.int64(431)

In [88]:
df.loc[(df['order_status']=='cancelled') & (df['sales']>0)]

Empty DataFrame
Columns: [order_id, order_date, customer_id, customer_name, region, state, city, category, subcategory, product, quantity, unit_price, discount, sales, cost, profit, payment_method, sales_channel, order_status]
Index: []

In [89]:
df.loc[(df['order_status']=='cancelled') & (df['sales']>0)].shape[0]

0

In [90]:
df.loc[(df['order_status']=='returned') & (df['sales']>0)]

Empty DataFrame
Columns: [order_id, order_date, customer_id, customer_name, region, state, city, category, subcategory, product, quantity, unit_price, discount, sales, cost, profit, payment_method, sales_channel, order_status]
Index: []

In [91]:
df.loc[(df['order_status']=='returned') & (df['sales']>0)].shape[0]

0

In [92]:
df.loc[df['profit'] > df['sales']]

Empty DataFrame
Columns: [order_id, order_date, customer_id, customer_name, region, state, city, category, subcategory, product, quantity, unit_price, discount, sales, cost, profit, payment_method, sales_channel, order_status]
Index: []

In [93]:
df.loc[df['profit'] > df['sales']].shape[0]

0

In [94]:
df.loc[df['profit']<0].shape[0]

536

In [95]:
df.loc[df['cost'] < 0].shape[0]

0

In [96]:
df.loc[df['discount'] < 0].shape[0]

0

In [97]:
df.loc[df['discount'] > 1].shape[0]

0

In [98]:
df.loc[df['quantity'] <= 0].shape[0]

0

In [99]:
df.loc[df['unit_price'] <= 0].shape[0]

0

In [100]:
df.loc[df['cost'] > df['sales']].shape[0]

536

In [101]:
df.isnull().sum()

order_id          0
order_date        0
customer_id       0
customer_name     0
region            0
state             0
city              0
category          0
subcategory       0
product           0
quantity          0
unit_price        0
discount          0
sales             0
cost              0
profit            0
payment_method    0
sales_channel     0
order_status      0
dtype: int64

In [102]:
df.duplicated().sum()

np.int64(0)

In [103]:
df.loc[(df['quantity'] <=0) | (df['unit_price']<0) | ((df['discount']<0) | (df['discount']>1) )].shape[0]

0

In [104]:
df.dtypes

order_id                     str
order_date        datetime64[us]
customer_id                int64
customer_name                str
region                       str
state                        str
city                         str
category                     str
subcategory                  str
product                      str
quantity                   int64
unit_price               float64
discount                 float64
sales                    float64
cost                     float64
profit                   float64
payment_method               str
sales_channel                str
order_status                 str
dtype: object

In [105]:
df.shape

(49975, 19)

In [106]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'customer_name', 'region',
       'state', 'city', 'category', 'subcategory', 'product', 'quantity',
       'unit_price', 'discount', 'sales', 'cost', 'profit', 'payment_method',
       'sales_channel', 'order_status'],
      dtype='str')

In [107]:
df.to_csv("../data/processed/sales_cleaned.csv", index=False)

In [108]:
df_check = pd.read_csv("../data/processed/sales_cleaned.csv")

In [109]:
df_check.shape

(49975, 19)

In [110]:
df_check.isnull().sum().sum()

np.int64(0)

# Final Data Cleaning Summary

## Cleaning Outcome

The raw retail transaction dataset was cleaned and transformed into an analysis-ready dataset while preserving the original source data.

### Final Dataset

- **Rows:** 49,975
- **Columns:** 19
- **Missing values:** 0
- **Duplicate records:** 0

### Cleaning Performed

- Preserved the original raw dataset and created a separate working copy.
- Standardized all column names to lowercase.
- Removed 150 exact duplicate records.
- Standardized inconsistent categorical values across Region, Payment Method, and Sales Channel.
- Converted mixed Order Date representations into a standardized datetime format.
- Treated missing Customer Name, City, and Payment Method values as `Unknown`.
- Treated missing Discount values as `0`.
- Removed records containing invalid quantities, unit prices, or discount values.
- Validated the relationships between Quantity, Unit Price, Discount, Sales, Cost, and Profit.
- Investigated financial inconsistencies between calculated and recorded Sales and Profit values without silently overwriting the original financial fields.
- Validated business rules related to order status, profitability, cost, quantity, price, and discount.
- Performed final data-quality validation after all cleaning operations.
- Saved the cleaned dataset as `data/processed/sales_cleaned.csv`.

## Output

The resulting dataset is ready for:

- Exploratory Data Analysis (EDA)
- Business KPI development
- Power BI reporting
- Business insights and recommendations
- Reusable Python data-processing workflows